### ISSUE TITLE
Does not work on me, can not create todo

### ISSUE THREAD

**Issue by Geolle** [Spectralgo/MSToDo-Quick-Add#1]
![image](https://user-images.githubusercontent.com/24875099/131317827-3f3308b4-58a5-4c04-88d5-60eebf899fec.png)
![image](https://user-images.githubusercontent.com/24875099/131317855-bca8df36-bf53-46b4-9979-aad64b354b69.png)

**Comment by Geolle** [comment]
``` log
2021-08-31 16:03:17.6117|ERROR|Wox.Core.Plugin.PluginManager|QueryForPlugin|Exception for plugin <MsTodo-Quick-Add> when query <i>|Exception begin --------------------
  System.AggregateException: One or more errors occurred.
  HResult: -2146233088
  Data: <ID> -> <36EDB8934A8341B8B2747E42763186A4>
  Data: <Name> -> <MsTodo-Quick-Add>
  Data: <PluginDirectory> -> <C:\Users\fcliq\AppData\Roaming\Wox\Plugins\MsTodo-Quick-Add-4e054e2e-c473-4254-a55a-b84ad25940e7>
  Data: <Website> -> <https://github.com/Spectralgo/MSToDo-Quick-Add>
  Source: mscorlib
  TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: CommonLanguageRuntimeLibrary
  TargetSite: TResult GetResultCore(Boolean)
  StackTrace: --------------------
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Wox.Plugin.MSToDo.MSToDo.Query(Query query)
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 174
   at Wox.Infrastructure.Stopwatch.StopWatchDebug(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 22
   at Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 172
  InnerException 1: ------------------------------------------------------------
    System.InvalidOperationException: Sequence contains no matching element
    HResult: -2146233079
    Source: System.Core
    TargetAssembly: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    TargetModule: System.Core.dll
    TargetSite: TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
    StackTrace: --------------------
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Wox.Plugin.MSToDo.MSToDo.<GetResult>d__7.MoveNext()
Exception end ------------------
```

**Comment by Tekknoman** [comment]
Same over here

**Comment by kuweiMaster** [comment]
Same over here

**Comment by kuweiMaster** [comment]
> Same over here

windows 11

**Comment by v1rusw0rm** [comment]
The default tasks list is searched by display name "Tasks": https://github.com/Spectralgo/MSToDo-Quick-Add/blob/main/Main.cs#L49
The name of this list depends on localization, so that's the issue probably.
Maybe it's better to use `wellknownListName=defaultList` instead of display name to get the list: https://docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-1.0#properties
